# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 08:45
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_auto_20151122_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ical_id',
            field=models.CharField(max_length=36, null=True, verbose_name='iCal identifier'),
        ),
    ]
