# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 12:20
from __future__ import unicode_literals

from django.db import migrations, models

import alexia.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_auto_20160407_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationdata',
            name='additional_data',
            field=models.TextField(null=True, verbose_name='additional data'),
        ),
        migrations.AlterField(
            model_name='authenticationdata',
            name='backend',
            field=models.CharField(max_length=50, verbose_name='authentication backend'),
        ),
        migrations.AlterField(
            model_name='authenticationdata',
            name='username',
            field=models.CharField(max_length=50, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='location',
            name='color',
            field=models.CharField(blank=True, max_length=6, validators=[alexia.core.validators.validate_color], verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='color',
            field=models.CharField(blank=True, max_length=6, validators=[alexia.core.validators.validate_color], verbose_name='color'),
        ),
    ]
