# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 14:10
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0011_auto_20160412_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='certificate'),
        ),
    ]
