# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 14:10
from django.db import migrations


def move_certificate_fk(apps, schema_editor):
    Profile = apps.get_model('organization', 'Profile')
    for profile in Profile.objects.all():
        if profile.certificate:
            profile.certificate.owner = profile.user
            profile.certificate.save()


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_certificate_owner'),
    ]

    operations = [
        migrations.RunPython(move_certificate_fk),
    ]
