# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-11 15:41
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_auto_20160419_1133'),
        ('organization', '0010_membership_is_active'),
    ]

    operations = [
    ]
