# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 12:52
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0018_auto_20170116_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='is_public',
        ),
    ]
