# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-24 09:41
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0019_auto_20170117_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=32, verbose_name='bartender nickname'),
        ),
    ]
