# Generated by Django 2.2.28 on 2024-09-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0024_saml_to_oidc_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='writeoff_enabled',
            field=models.BooleanField(default=False, verbose_name='writeoff enabled'),
        ),
    ]
