# Generated by Django 4.2.26 on 2025-12-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0025_organization_writeoff_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='age_check_api_endpoint',
            field=models.URLField(blank=True, null=True, verbose_name='age check API endpoint'),
        ),
        migrations.AddField(
            model_name='organization',
            name='age_check_api_key',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='age check API key'),
        ),
        migrations.AddField(
            model_name='organization',
            name='age_check_enabled',
            field=models.BooleanField(default=False, verbose_name='age check enabled'),
        ),
    ]
