# Generated by Django 4.2.26 on 2026-07-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0026_organization_age_check_api_endpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='card_registration_url',
            field=models.URLField(blank=True, null=True, verbose_name='card registration URL'),
        ),
    ]
