# Generated by Django 6.1 on 2026-09-28 22:00

import alexia.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0027_organization_card_registration_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='color',
            new_name='color_dark',
        ),
        migrations.AlterField(
            model_name='organization',
            name='color_dark',
            field=models.CharField(blank=True, max_length=6, validators=[alexia.core.validators.validate_color], verbose_name='dark color (used in light mode)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='color_light',
            field=models.CharField(blank=True, max_length=6, validators=[alexia.core.validators.validate_color], verbose_name='light color (used in dark mode)'),
        ),
    ]
