# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-01 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_auto_20160419_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shortcut',
            field=models.CharField(blank=True, max_length=1, verbose_name='shortcut'),
        ),
    ]
