# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-29 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_django18'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumption',
            name='group',
        ),
        migrations.RemoveField(
            model_name='consumption',
            name='product',
        ),
        migrations.RemoveField(
            model_name='eventconsumption',
            name='event',
        ),
        migrations.RemoveField(
            model_name='stockcount',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='stockcount',
            name='products',
        ),
        migrations.RemoveField(
            model_name='stockcount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stockproductamount',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockproductamount',
            name='stockcount',
        ),
        migrations.DeleteModel(
            name='Consumption',
        ),
        migrations.DeleteModel(
            name='EventConsumption',
        ),
        migrations.DeleteModel(
            name='StockCount',
        ),
        migrations.DeleteModel(
            name='StockProduct',
        ),
        migrations.DeleteModel(
            name='StockProductAmount',
        ),
    ]
