# Generated by Django 1.10.8 on 2017-12-04 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
      migrations.RunSQL(
        "ALTER TABLE eventlog_log RENAME TO general_auditlog",
        "ALTER TABLE general_auditlog RENAME TO eventlog_log",
        state_operations=[
            migrations.CreateModel(
                name='Auditlog',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                    ('action', models.CharField(db_index=True, max_length=50)),
                    ('object_id', models.PositiveIntegerField(null=True)),
                    ('extra', jsonfield.fields.JSONField()),
                    ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
                    ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ],
                options={
                    'ordering': ['-timestamp'],
                },
            ),
        ]),
    ]
