# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 09:33
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_auto_20160412_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Designates if tenders can sign up for this event.', verbose_name='enrolment closed'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_risky',
            field=models.BooleanField(default=False, help_text='Designates that this event should be marked as risky.', verbose_name='risky'),
        ),
        migrations.AlterField(
            model_name='event',
            name='option',
            field=models.BooleanField(default=False, help_text='Designates that this event is not definitive yet.', verbose_name='option'),
        ),
    ]
