# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 22:26
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0012_auto_20161208_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardreservation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='standardreservation',
            name='organization',
        ),
        migrations.DeleteModel(
            name='StandardReservation',
        ),
    ]
