# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 22:40
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0013_auto_20161227_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailtemplate',
            name='send_at',
        ),
    ]
