# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 21:51
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0015_auto_20170116_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pricegroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='billing.PriceGroup', verbose_name='pricegroup'),
        ),
    ]
