# Generated by Django 2.2.25 on 2022-06-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0019_auto_20210326_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='position',
            field=models.IntegerField(default=1, verbose_name='position'),
        ),
    ]
