# Generated by Django 2.2.28 on 2024-09-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0020_availability_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['position'], 'verbose_name': 'availability type', 'verbose_name_plural': 'availability types'},
        ),
    ]
