# Generated by Django 2.2.28 on 2024-10-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    
    dependencies = [
        ('scheduling', '0020_availability_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['position'], 'verbose_name': 'availability type', 'verbose_name_plural': 'availability types'},
        ),
        migrations.AddField(
            model_name='bartenderavailability',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=100, verbose_name='comment'),
        ),
    ]
