# Generated by Django 6.1 on 2026-09-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0022_auto_20241001_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='If checked, tenders will not be able to sign up for this event (note: tenders get e-mailed about events with open enrollments).', verbose_name='tender enrollment closed'),
        ),
    ]
