# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-07 15:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0003_auto_20161206_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptionform',
            name='completed_at',
            field=models.DateTimeField(null=True, verbose_name='completed at'),
        ),
        migrations.AlterField(
            model_name='unitentry',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='weightentry',
            name='flow_start',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='flowmeter start'),
        ),
    ]
