# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 09:33
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_auto_20160412_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='synchronized',
            field=models.BooleanField(default=False, help_text='Designates whether this transaction is imported by the organization.', verbose_name='synchronized'),
        ),
    ]
