# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 21:51
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_auto_20170116_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-placed_at'], 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='permanentproduct',
            options={'ordering': ['organization', 'position'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='pricegroup',
            options={'ordering': ['organization', 'name'], 'verbose_name': 'price group', 'verbose_name_plural': 'price groups'},
        ),
        migrations.AlterModelOptions(
            name='productgroup',
            options={'ordering': ['organization', 'name'], 'verbose_name': 'product group', 'verbose_name_plural': 'product groups'},
        ),
        migrations.AlterModelOptions(
            name='sellingprice',
            options={'verbose_name': 'selling price', 'verbose_name_plural': 'selling prices'},
        ),
        migrations.RemoveField(
            model_name='authorization',
            name='account',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.PositiveSmallIntegerField(verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='billing.Order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='rfidcard',
            name='managed_by',
            field=models.ManyToManyField(to='organization.Organization', verbose_name='managed by'),
        ),
        migrations.AlterField(
            model_name='rfidcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='temporaryproduct',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporaryproducts', to='scheduling.Event', verbose_name='event'),
        ),
    ]
