# Generated by Django 2.1.15 on 2021-03-26 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_rfid_cards_set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='organization.Organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='permanentproduct',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='organization.Organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='permanentproduct',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='billing.Product'),
        ),
        migrations.AlterField(
            model_name='permanentproduct',
            name='productgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.ProductGroup', verbose_name='product group'),
        ),
        migrations.AlterField(
            model_name='pricegroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricegroups', to='organization.Organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productgroups', to='organization.Organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='sellingprice',
            name='pricegroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.PriceGroup', verbose_name='price group'),
        ),
        migrations.AlterField(
            model_name='sellingprice',
            name='productgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.ProductGroup', verbose_name='product group'),
        ),
        migrations.AlterField(
            model_name='temporaryproduct',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='billing.Product'),
        ),
    ]
