# Generated by Django 2.2.28 on 2024-09-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_writeoffcategory_writeofforder_writeoffpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeoffcategory',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
