# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_enrollclosed_mail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['organization', 'name'], 'verbose_name': 'availability type', 'verbose_name_plural': 'availability types'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-starts_at'], 'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AlterModelOptions(
            name='mailtemplate',
            options={'ordering': ['organization', 'name'], 'verbose_name': 'mail template', 'verbose_name_plural': 'mail templates'},
        ),
        migrations.AlterField(
            model_name='event',
            name='tender_comments',
            field=models.TextField(blank=True, verbose_name='tender comments'),
        ),
    ]
