# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-28 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_auto_20160419_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is deleted'),
        ),
    ]
