# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-11 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_auto_20160419_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Designates if tenders can sign up for this event.', verbose_name='tender enrollment closed'),
        ),
    ]
