# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-15 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0004_auto_20161207_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumptionproduct',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is currently active'),
        ),
    ]
